<a href="https://colab.research.google.com/github/Silpa12345/Deep_learning/blob/main/Task_4_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch


x = torch.Tensor([
    [4, 0, 2, 1],
    [0, 1, 1, 2],
    [1, 0, 1, 0]
])

w_q = torch.Tensor([
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 1],
    [1, 0, 0]
])

w_k = torch.Tensor([
    [1, 0, 1],
    [1, 1, 0],
    [1, 1, 1],
    [0, 0, 1]
])

w_v = torch.Tensor([
    [0, 0, 2],
    [3, 0, 0],
    [1, 5, 0],
    [0, 1, 0]
])

print(x)
print(w_q)
print(w_k)
print(w_v)

tensor([[4., 0., 2., 1.],
        [0., 1., 1., 2.],
        [1., 0., 1., 0.]])
tensor([[0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 1.],
        [1., 0., 0.]])
tensor([[1., 0., 1.],
        [1., 1., 0.],
        [1., 1., 1.],
        [0., 0., 1.]])
tensor([[0., 0., 2.],
        [3., 0., 0.],
        [1., 5., 0.],
        [0., 1., 0.]])


In [3]:
# TODO: Derive queries, keys and values
queries =torch.matmul(x, w_q)
keys = torch.matmul(x, w_k)
values = torch.matmul(x, w_v)

print(queries)
print(keys)
print(values)

tensor([[1., 2., 6.],
        [2., 2., 1.],
        [0., 1., 2.]])
tensor([[6., 2., 7.],
        [2., 2., 3.],
        [2., 1., 2.]])
tensor([[ 2., 11.,  8.],
        [ 4.,  7.,  0.],
        [ 1.,  5.,  2.]])


In [4]:
# TODO: Calculate attention scores
attn_scores = torch.matmul(queries, keys.T)
attn_scores

tensor([[52., 24., 16.],
        [23., 11.,  8.],
        [16.,  8.,  5.]])

In [5]:
# TODO: Calculate softmax
from torch.nn.functional import softmax

attn_scores_softmax = softmax(attn_scores, dim=1)
attn_scores_softmax

tensor([[1.0000e+00, 6.9144e-13, 2.3195e-16],
        [9.9999e-01, 6.1442e-06, 3.0590e-07],
        [9.9965e-01, 3.3534e-04, 1.6696e-05]])

In [6]:
# TODO: Multiply softmax with values
weighted_values = torch.matmul(attn_scores_softmax, values)
weighted_values

tensor([[ 2.0000, 11.0000,  8.0000],
        [ 2.0000, 11.0000,  7.9999],
        [ 2.0007, 10.9986,  7.9972]])

In [7]:
# TODO: Sum weighted values
outputs = weighted_values.sum(dim=1)
outputs

tensor([21.0000, 20.9999, 20.9964])